### ISSUE TITLE
CalendarList super slow rendering in iOS (RN 0.47.2)

### ISSUE THREAD

**Issue by hernancorigliano** [wix/react-native-calendars#152]
## Description

CalendarList component renders super slow and it stops rendering after some time. (iOS)

## Expected Behavior

I create a CalendarList component and display it in my root view. I can see the calendar list, scroll it and use it.

## Observed Behavior

I create a CalendarList component and render it in the my root view. The calendar works fine in simulator, but on iPad and iPhone devices it starts rendering very slow, and some times it just get stuck in big Month names and not render the calendars at all. (Using 4 calendar in the list). It is imposible to use it.

## Environment

* `npm ls react-native-calendars`:
   React-native-calendars@1.5.8

* `npm ls react-native`:
   react-native@0.47.2

1. Phone/emulator/simulator & version:

Simulator: iPhone 6s
Devices: iPhone 5S, iPad Mini , iPhone 6

## Reproducible Demo
Just install the npm package and try to display a CalendarList component.
Example:

```
<CalendarList
             minDate={'2017-08-22'}
             maxDate={'2017-09-02'}
             firstDay={1}
             pastScrollRange={0}
             futureScrollRange={4}
             markingType={'interactive'}            
         />

**Comment by tautvilas** [comment]
Hello, please check if problems have not been solved in 1.6.0 with FlatList implementation

**Comment by dseawel** [comment]
This is still very slow with v1.6.0 and latest version (1.6.2).

**Comment by tautvilas** [comment]
I have not reproduces such behavior in iphone 6.. Can other users confirm this problem? Maybe it's related to displaying only 4 calendars? What if you don't use marking? Does performance improve?

**Comment by dseawel** [comment]
I've tried a few configurations including the simple one in the examples and on physical devices and simulators. The issue I'm seeing is that when a new calendar is scrolled into view it flashes a few times between the full month calendar and the Month/Year overlay before finally showing the calendar.

![renderissue](https://user-images.githubusercontent.com/1859611/30557601-75c9d26c-9c74-11e7-9be3-4f59be854556.gif)


My example: 
`<CalendarList
        pastScrollRange={12}
        futureScrollRange={12}
        current={'2017-09-18'}
      />`

**Comment by mirrorshades** [comment]
@dseawel do you have slow animations enabled?

**Comment by dseawel** [comment]
Unfortunately, no. Here it is about as optimized as I can get it. It's mostly an issue when you flick as you scroll. 

The example in Expo is very smooth on my phone. I was hoping someone could help me recreate that configuration.

![renderissue2](https://user-images.githubusercontent.com/1859611/30558676-e19b666a-9c77-11e7-8671-e7a51942867e.gif)

**Comment by tautvilas** [comment]
So Expo example works good? What kind of navigation do you use? React native navigation or react navigation? What is containing the calendar? I suspect the problem is in the containing view. It would be interesting to add console.log to onViewableItemsChanged in calendar-list index. There should be something weird going on there..

**Comment by tautvilas** [comment]
At least from your example it looks like the problem is that veiwableItems event is only properly fired when calendar list stops scrolling.

**Comment by dseawel** [comment]
I'm using react-navigation. To forgo that I placed the control directly into app/index.js. I'm not sure how to override the `onViewableItemsChanged` on the FlatList you use but I did console.log the `onVisibleMonthsChange` in the example below. Does it normally switch between 0 and 2+ items that frequently?

[https://vimeo.com/234379916](https://vimeo.com/234379916)

PS - Thanks for your quick response to this. I'm really excited about getting to use this awesome control.

**Comment by dseawel** [comment]
FWIW, that first warning was this `VirtualizedList: You have a large list that is slow to update - make sure your renderItem function renders components that follow React performance best practices like PureComponent, shouldComponentUpdate, etc. `

**Comment by hernancorigliano** [comment]
Hi there. Just my two cents. I could not find any good calendar out there, and this one was pretty much what i needed. But the slow performance on the devices was a problem. So i built my own calendar list, things is i run into similar performance issues. My calendar list is the simplest a calendar can be, but the problem is that a calendar has a lot of React Components, and it seems the JS thread cannot handle so many components updates. I have optimized my calendar to in every aspect and have come to a descent performance on old devices and good one in new. I am using a VirtualizedList by the way and some caching and preloading. I want to share it on github anytime soon. Cheers

**Comment by tautvilas** [comment]
@dseawel I have recorded onViewableItemsChanged in example project. Your video does not look good. This is how events should behave. There is some problem/bug with react native itself or containing view of calendar list. Looks like events are being throttled and only fired after scrolling stops.

![viewable](https://user-images.githubusercontent.com/1044090/30578944-0ed6fb42-9d1f-11e7-85d7-be8716c5fe04.gif)

**Comment by dseawel** [comment]
Good news, it works great on RN v0.48.3.

I init'ed a new react-native project (v0.48.3) and this control work just fine. It's taken me this long to upgrade all my dependencies on my active project to work with RN 0.48.3 but I can confirm that it's super fast! 

As far as I'm concerned, you can close this one.

**Comment by hernancorigliano** [comment]
@dseawel have you tried on actual devices like iPhone 5s or iPhone 6? Did it become solved only by upgrading to RN 0.48.3? Which RN version did you update from? Thanks!

**Comment by rvignesh89** [comment]
I understand that this bug has been closed for a while. But I faced the same issue and have figured out the root cause for this problem. Just posting my findings for future visitors

The issue is because of a bug in RN `VirtualizedList` which has been fixed [here](https://github.com/facebook/react-native/pull/14162/files). I notice that this commit exists after version 0.46. So to answer @hernancorigliano's question If you are before RN 0.46.0 you'll face this issue(I haven't actually upgraded to 0.46 to test the fix out. I myself am at 0.45.1 right now).

The problem in react-native-calendars occurs  when CalendarList `onViewableItemsChanged` is fired with an empty `viewableItems` as seen here.

![screen shot 2018-02-21 at 9 36 55 pm](https://user-images.githubusercontent.com/2748970/36482938-b7f1bf14-174f-11e8-80a8-f903d884675b.png)

This is the same log as seen in @dseawel's video. In the video by @tautvilas this does not happen.

**Comment by hernancorigliano** [comment]
I am on RN 0.51  and still have a slow performance calendar :(

**Comment by rvignesh89** [comment]
That’s strange because I upgraded to 0.46.0 yesterday and can confirm that there is no more lagging for me.

**Comment by onosol** [comment]
Using Agenda view only on RN 0.55.3 and it has noticable lag when rendering.... :(
Worked great when I was on RN 0.43.....
