### ISSUE TITLE
Cannot read property 'toString' of undefined in getUTCMode

### ISSUE THREAD

**Issue by tapz** [wix/react-native-calendars#2046]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

WeekCalendar and ExpandableCalendar don't work. Just getting an error.

## Expected Behavior

To see a calendar.

## Observed Behavior

An error

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Cannot read property 'toString' of undefined

140 | proto. getUTCMode = methodize (getUTCMode);
141 | function getUTCMode(xdate){
> 142 | return date[0].toString === toUTCString;
143 | 1:

Call Stack
getUTCMode
×date.is:142:9
<anonvmous>
×date. js:186:39
getDate
new.is:74:24
getDatesArray
new.is:87:26
WeekCalendar
new.is:21:53
See 18 more frames
```

## Environment

Please run these commands in the project folder and fill in their results:

react-native-calendars@1.1289.0
react-native@0.70.1

Also specify:

1. Device/emulator/simulator & OS version:

Nokia X1
Android 12

## Reproducible Demo

`<WeekCalendar />`

## Screenshots

![screencap](https://user-images.githubusercontent.com/11726387/192739989-e9e828a1-99ad-4b87-9274-59a8972d7165.png)

**Comment by ziudeso** [comment]
Same issue expo 46

**Comment by podger** [comment]
Same here with version lib version: ^1.1275.0 and reacat-native 0.70.4

**Comment by podger** [comment]
Ok basically I figured it out for my case. Just lack of documentation.

`<ExpandableCelendar>` and `<WeekCalendar>` need to be wrapped with `<CalendarProvider date={'2022-10-28'} >`

The _undefined_ is from the missing date that the components try to retrieve from the context, not from the props.

[Check this example out](https://github.com/wix/react-native-calendars/blob/master/example/src/screens/expandableCalendarScreen.tsx)

**Comment by JanmyLo** [comment]
> Ok basically I figured it out for my case. Just lack of documentation.
> 
> `<ExpandableCelendar>` and `<WeekCalendar>` need to be wrapped with `<CalendarProvider date={'2022-10-28'} >`
> 
> The _undefined_ is from the missing date that the components try to retrieve from the context, not from the props.
> 
> [Check this example out](https://github.com/wix/react-native-calendars/blob/master/example/src/screens/expandableCalendarScreen.tsx)

this work in my case!

**Comment by corgiLoaf** [comment]
> Ok basically I figured it out for my case. Just lack of documentation.
> 
> `<ExpandableCelendar>` and `<WeekCalendar>` need to be wrapped with `<CalendarProvider date={'2022-10-28'} >`
> 
> The _undefined_ is from the missing date that the components try to retrieve from the context, not from the props.
> 
> [Check this example out](https://github.com/wix/react-native-calendars/blob/master/example/src/screens/expandableCalendarScreen.tsx)

You are my savior

**Comment by palo-landrae** [comment]
Still issue on latest version. Documentation says
date
  Initial date in 'yyyy-MM-dd' format
  string
  
i get 
141 | function getUTCMode(xdate){
142 | return xdate[0].toString === toUTCString;
>143 | }:

**Comment by jeveloper** [comment]
FYI it's fixed, I think I pushed a fix a while back.

**Comment by Ark1011** [comment]
> Ok basically I figured it out for my case. Just lack of documentation.
> 
> `<ExpandableCelendar>` and `<WeekCalendar>` need to be wrapped with `<CalendarProvider date={'2022-10-28'} >`
> 
> The _undefined_ is from the missing date that the components try to retrieve from the context, not from the props.
> 
> [Check this example out](https://github.com/wix/react-native-calendars/blob/master/example/src/screens/expandableCalendarScreen.tsx)


this was the case

**Comment by misaelriojasftf** [comment]
it's happening again even when using the provider 

<img width="694" alt="image" src="https://github.com/user-attachments/assets/aa22ad3c-e647-41d2-be12-b732c2c9c348">

**Comment by soyalexrc** [comment]
> Ok basically I figured it out for my case. Just lack of documentation.
> 
> `<ExpandableCelendar>` and `<WeekCalendar>` need to be wrapped with `<CalendarProvider date={'2022-10-28'} >`
> 
> The _undefined_ is from the missing date that the components try to retrieve from the context, not from the props.
> 
> [Check this example out](https://github.com/wix/react-native-calendars/blob/master/example/src/screens/expandableCalendarScreen.tsx)

I am passing 

 date={format(new Date(), 'yyyy-MM-dd')}
 
 date={new Date().toISOString().split('T')[0]}
 
 and i still get the error, i need this value to be dynamic...
 
 Is this the case to anyone else?

**Comment by jeveloper** [comment]
@soyalexrc hi Alex, 
Can you confirm what library is format from?
Ideally a short snippet showing in what context youre doing this. 
personally I would advise writing code without inferring arrays, too many assumptions create bad code. e.g. some object[0] 
That crashes the whole app as oppose to showing some empty field. 


I haven't used this library for almost 2 years though I patched this area long ago. 

This is what handles the props for date : const dateData = date ? xdateToData(date) : undefined;

hope its helpful, and happy new year!
